import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { App } from "@/context/AppContext";
import Navbar from "../components/common/Navbar";
import Sidebar from "@/components/common/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <App>
          <div className="fixed top-0 w-full">
            <Navbar />
          </div>
          <div className="flex w-full justify-end items-start">
            <div className="fixed left-0 mt-24">
              <Sidebar />
            </div>
            <div className="w-[calc(100vw-280px)]">{children}</div>
          </div>
        </App>
      </body>
    </html>
  );
}
